version: 2.0
jobs:
  build:
    docker: 
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - run: echo "Hello world!"
  test1:
    docker: 
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - run: echo "Hello again!"
  test2:
    docker: 
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - run: echo "Hello for the third time!"
  deploy:
    docker: 
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - run: echo "Finally!"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - deploy:
          requires:
            - test2